name: Deploy to GOV.UK PaaS

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy-to-paas:
    runs-on: ubuntu-latest
    environment: live_paas
    name: Deploy to GOV.UK PaaS
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        cd main/
        
        python -m pip install -r requirements.txt -r requirements-dev.txt
        make test
      
    - run: |
        cd main/

        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf7-cli

        cf7 api https://api.cloud.service.gov.uk
        cf7 auth "${{ secrets.PAAS_USER }}" "${{ secrets.PAAS_PASS }}"
        cf target -o gds-security -s cyber-sec-sandbox

        make deploy
